function runTyper() {

 typer('.typertext', 55)
		.cursor({blink: 'soft'})
		.line("I'd like to say that I'm a pretty skilled Web Developer.")
		.pause(2000)
		.back(15)
		.continue(" iOS Developer.")
		.pause(2000)
		.back(15)
		.continue(" Photographer.")
		.pause(2000)
		.back(14)
		.continue(" Designer.")
		.pause(2000)
		.back('all')
		.continue("I'll do whatever you need, really. Can't help it, I'm an overachiever.")
		.pause(5000)
		.empty()
		.end()
}

 typer('.typertext', 55)
		.cursor({blink: 'soft'})
		.line("I'd like to say that I'm a pretty skilled Web Developer.")
		.pause(2000)
		.back(15)
		.continue(" iOS Developer.")
		.pause(2000)
		.back(15)
		.continue(" Photographer.")
		.pause(2000)
		.back(14)
		.continue(" Designer.")
		.pause(2000)
		.back('all')
		.continue("I'll do whatever you need, really. Can't help it, I'm an overachiever.")
		.pause(5000)
		.empty()
		.end()
		
window.setInterval(runTyper, 28700);